-- Enable RLS on all tables
-- Setup Supabase Auth is assumed to be handled by the platform, but we create tables here.

-- 1. TABLA ARTICULOS
CREATE TABLE IF NOT EXISTS public.articulos (
    id_sku TEXT PRIMARY KEY,
    id_sku_capataz TEXT,
    descripcion TEXT,
    familia TEXT,
    tipo_molde TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('america/argentina/buenos_aires', now())
);
ALTER TABLE public.articulos ENABLE ROW LEVEL SECURITY;

-- 2. TABLA PLAN DE PRODUCCION
CREATE TABLE IF NOT EXISTS public.plan_produccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    tipo_proyeccion TEXT, -- 'semanal', 'mensual', 'fija'
    cantidad_plan INTEGER NOT NULL DEFAULT 0,
    linea TEXT NOT NULL,
    id_sku TEXT REFERENCES public.articulos(id_sku),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('america/argentina/buenos_aires', now())
);
ALTER TABLE public.plan_produccion ENABLE ROW LEVEL SECURITY;

-- 3. TABLA PRODUCCION REAL
CREATE TABLE IF NOT EXISTS public.produccion_real (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_produccion DATE NOT NULL,
    cantidad_real INTEGER NOT NULL DEFAULT 0,
    linea TEXT NOT NULL,
    id_sku TEXT REFERENCES public.articulos(id_sku),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('america/argentina/buenos_aires', now())
);
ALTER TABLE public.produccion_real ENABLE ROW LEVEL SECURITY;

-- 4. TABLA FERIADOS ARGENTINA
CREATE TABLE IF NOT EXISTS public.feriados_ar (
    fecha DATE PRIMARY KEY,
    descripcion TEXT,
    tipo TEXT, -- 'inmutable', 'trasladable', etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('america/argentina/buenos_aires', now())
);
ALTER TABLE public.feriados_ar ENABLE ROW LEVEL SECURITY;


-- 5. RLS POLICIES (Strict: Auth Required)

-- Articulos: Read All Auth, Write Auth
CREATE POLICY "Enable read access for authenticated users" ON public.articulos
    FOR SELECT TO authenticated USING (true);

-- Plan: Read All Auth
CREATE POLICY "Enable read access for authenticated users" ON public.plan_produccion
    FOR SELECT TO authenticated USING (true);

-- Real: Read All Auth
CREATE POLICY "Enable read access for authenticated users" ON public.produccion_real
    FOR SELECT TO authenticated USING (true);
    
-- Feriados: Read All Auth
CREATE POLICY "Enable read access for authenticated users" ON public.feriados_ar
    FOR SELECT TO authenticated USING (true);

-- (Optional) Write policies can be added if the dashboard needs to write back.
-- specific write policies omitted for brevity, assuming data ingestion happens via other authenticated means or admin.


-- 6. VISTA DE INTELIGENCIA DE NEGOCIO (v_dashboard_main)
-- Logic: 
-- - Join Plan and Real on Date + Linea + SKU (Full Outer Join or Union strategy usually better for dates gaps)
-- - Calculate Cumulative Plan considering Feriados (Capacity = 0 if Holiday)
-- - Calculate Cumulative Real
-- - Calculate Ritmo (Average Real last 7 active days) for Time Delay estimation

CREATE OR REPLACE VIEW public.v_dashboard_main AS
WITH 
dates_scope AS (
    SELECT DISTINCT fecha FROM public.plan_produccion
    UNION 
    SELECT DISTINCT fecha_produccion AS fecha FROM public.produccion_real
),
daily_metrics AS (
    SELECT 
        d.fecha,
        COALESCE(p.linea, r.linea) as linea,
        COALESCE(p.id_sku, r.id_sku) as id_sku,
        COALESCE(SUM(p.cantidad_plan), 0) as plan_dia,
        COALESCE(SUM(r.cantidad_real), 0) as real_dia,
        CASE WHEN f.fecha IS NOT NULL THEN 0 ELSE 1 END as es_laborable
    FROM dates_scope d
    LEFT JOIN public.plan_produccion p ON p.fecha = d.fecha
    LEFT JOIN public.produccion_real r ON r.fecha_produccion = d.fecha 
           AND (p.linea IS NULL OR r.linea = p.linea) -- simple join heuristic
           AND (p.id_sku IS NULL OR r.id_sku = p.id_sku)
    LEFT JOIN public.feriados_ar f ON f.fecha = d.fecha
    GROUP BY d.fecha, COALESCE(p.linea, r.linea), COALESCE(p.id_sku, r.id_sku), f.fecha
),
accumulated AS (
    SELECT
        fecha,
        linea,
        id_sku,
        plan_dia,
        real_dia,
        es_laborable,
        SUM(CASE WHEN es_laborable = 1 THEN plan_dia ELSE 0 END) OVER (PARTITION BY linea, id_sku ORDER BY fecha) as plan_acumulado,
        SUM(real_dia) OVER (PARTITION BY linea, id_sku ORDER BY fecha) as real_acumulado
    FROM daily_metrics
),
ritmo_7d AS (
    -- Ritmo promedio de los ultimos 7 dias con produccion > 0
    SELECT
        linea,
        AVG(cantidad_real) as avg_ritmo
    FROM public.produccion_real
    WHERE fecha_produccion >= (CURRENT_DATE - INTERVAL '7 days')
    GROUP BY linea
)
SELECT 
    a.fecha,
    a.linea,
    a.id_sku,
    a.plan_dia,
    a.real_dia,
    a.plan_acumulado,
    a.real_acumulado,
    (a.real_acumulado - a.plan_acumulado) as desvio_unidades,
    COALESCE(rit.avg_ritmo, 1) as ritmo_promedio, -- avoid div by 0
    CASE 
        WHEN (a.plan_acumulado - a.real_acumulado) <= 0 THEN 0
        ELSE ROUND(((a.plan_acumulado - a.real_acumulado) / NULLIF(COALESCE(rit.avg_ritmo, 1), 0))::numeric, 2)
    END as dias_atraso
FROM accumulated a
LEFT JOIN ritmo_7d rit ON rit.linea = a.linea;

-- Grant access to view
GRANT SELECT ON public.v_dashboard_main TO authenticated;
